FROM mysql
# Add a database
ENV MYSQL_DATABASE ibm
ENV MYSQL_ROOT_PASSWORD=password 
EXPOSE 3306
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/
